export const easyCountries = [
  "United States",
  "Canada",
  "Brazil",
  "China",
  "India",
  "Australia",
  "Russia",
  "Japan",
  "United Kingdom",
  "France",
  "Germany",
  "Italy",
  "Mexico",
  "Spain",
  "South Africa",
  "Argentina",
  "Egypt",
  "Turkey",
  "South Korea",
  "Indonesia",
  "Netherlands",
  "Vietnam",
  "Thailand",
  "Colombia",
  "Saudi Arabia",
  "Chile",
  "Poland",
  "Sweden",
  "Ukraine",
  "Philippines",
  "Malaysia",
  "Greece",
  "Morocco",
  "Peru",
  "Venezuela",
  "Norway",
  "New Zealand",
  "Pakistan",
  "Nigeria",
  "Kenya",
  "Iraq",
  "Israel",
  "Belgium",
  "Switzerland",
  "Austria",
  "Ireland",
  "Portugal",
  "Czechia",
  "Hungary",
  "Romania",
  "Denmark",
];

export const mediumCountries = [
  "Finland",
  "Croatia",
  "Jordan",
  "Lebanon",
  "Kazakhstan",
  "Uzbekistan",
  "Slovakia",
  "Serbia",
  "Bulgaria",
  "Lithuania",
  "Latvia",
  "Estonia",
  "Slovenia",
  "Iceland",
  "Qatar",
  "Kuwait",
  "Bahrain",
  "Oman",
  "Georgia",
  "Azerbaijan",
  "Armenia",
  "Moldova",
  "Cuba",
  "Panama",
  "Uruguay",
  "Costa Rica",
  "El Salvador",
  "Honduras",
  "Jamaica",
  "Trinidad and Tobago",
  "Botswana",
  "Namibia",
  "Angola",
  "Ghana",
  "Ethiopia",
  "Tanzania",
  "Uganda",
  "Rwanda",
  "Mozambique",
  "Zambia",
  "Zimbabwe",
  "Papua New Guinea",
  "Albania",
  "Montenegro",
  "North Macedonia",
  "Malta",
  "Cyprus",
  "Libya",
  "Sudan",
  "North Korea",
  "Myanmar",
  "Cambodia",
  "Laos",
  "Sri Lanka",
  "Nepal",
  "Fiji",
  "Mauritius",
  "Madagascar",
  "Ecuador",
  "Bolivia",
  "Paraguay",
  "Guatemala",
  "Dominican Republic",
  "Barbados",
  "Antigua and Barbuda",
  "Saint Vincent and the Grenadines",
  "Bahamas",
  "Syria",
  "Tunisia",
  "Ivory Coast",
  "Senegal",
  "Cameroon",
  "Central African Republic",
  "Republic of Congo",
  "Democratic Republic of Congo",
  "Burkina Faso",
  "Mali",
  "Niger",
  "Chad",
  "Somalia",
  "South Sudan",
  "Guinea",
  "Gabon",
  "Tajikistan",
  "Kyrgyzstan",
  "Mongolia",
  "Malawi",
  "Lesotho",
  "Swaziland (Eswatini)",
];

export const hardCountries = [
  "Luxembourg",
  "Bhutan",
  "Nauru",
  "Vanuatu",
  "San Marino",
  "Togo",
  "Burundi",
  "Djibouti",
  "Andorra",
  "Liechtenstein",
  "Monaco",
  "Suriname",
  "Timor-Leste",
  "Tuvalu",
  "Palau",
  "Seychelles",
  "Kiribati",
  "Marshall Islands",
  "Micronesia",
  "Solomon Islands",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Comoros",
  "Sao Tome and Principe",
  "Cape Verde",
  "Gambia",
  "Guinea-Bissau",
  "Benin",
  "Equatorial Guinea",
  "Maldives",
  "Mauritania",
  "Liberia",
  "Sierra Leone",
  "Eritrea",
  "Western Sahara",
  "Faroe Islands",
  "Greenland",
  "Yemen",
  "Haiti",
  "Grenada",
  "Montserrat",
  "Anguilla",
  "Aruba",
  "Curaçao",
  "Guadeloupe",
  "Martinique",
  "Mayotte",
  "French Guiana",
  "French Polynesia",
  "Guam",
  "Samoa",
  "Vatican City",
  "Kosovo",
  "Turkmenistan",
  "Tonga",
  "Syria",
  "Turks and Caicos Islands",
];
